[project]
name = "server"
version = "0.1.0"
description = "The backend for Scatterbrain"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask-cors>=5.0.0",
    "flask>=3.1.0",
    "numpy>=2.2.0",
    "flask-session>=0.8.0",
    "requests>=2.32.3",
]
