name: Deploy backend on PythonAnywhere

on:
    push:
        branches:
            - test-deploy

jobs:
  build-frontend:
    name: Build React app
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v2
          
        - name: Install Node.js
          uses: actions/setup-node@v3
          
        - name: Install deps
          uses: bahmutov/npm-install@v1
          
        - name: Build project
          run: npm run build
          
        - name: Upload production files
          uses: actions/upload-artifacts@v3
          with:
            name: prod-files
            path: ./dist
            
  deploy-frontend:
    name: Deploy React app
    needs: build-frontend
    runs-on: ubuntu-latest
    
    steps:
        - name: Download production files
          uses: actions/download-artifacts@v3
          with:
            name: prod-files
            path: ./dist
        - name: Deploy to GitHub pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GH_TOKEN }}
            publish_dir: ./dist
    
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        
        # ... uploading files ...
        
        - name: Reload webapp
          run: |
            curl -X POST "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/webapps/${{ secrets.P_DNAME }}/reload/" \
                 -H "Authorization: Token ${{ secrets.PA_TOKEN }}"