name: Manual Trigger Example

on:
  workflow_dispatch:

jobs:
  post_request_job:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Store secrets in a file
      - name: Store secrets in a file
        run: |
          echo "PA_USERNAME=${{ secrets.PA_USERNAME }}" > secrets.txt
          echo "PA_DNAME=${{ secrets.PA_DNAME }}" >> secrets.txt
          echo "PA_TOKEN=${{ secrets.PA_TOKEN }}" >> secrets.txt
          echo "Secrets have been saved to secrets.txt."

      # Step 2: Upload the secrets.txt file as an artifact
      - name: Upload secrets as artifact
        uses: actions/upload-artifact@v3
        with:
          name: secrets-file
          path: secrets.txt

      # Step 3: Make POST request to reload webapp (if needed)
      - name: Make POST request to reload webapp
        run: |
          response=$(curl -X POST "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/webapps/${{ secrets.PA_DNAME }}/reload/" \
          -H "Authorization: Token ${{ secrets.PA_TOKEN }}" \
          -H "Content-Type: application/json" -w "%{http_code}")
          echo "Response code: $response"
